export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";

export const DANG_KY_ACTION = "DANG_KY_ACTION";

export const LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION = "LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION";

export const DISPLAY_LOADING = "DISPLAY_LOADING";

export const HIDE_LOADING = "HIDE_LOADING";

export const LAY_DANH_SACH_CONG_VIEC_ACTION = "LAY_DANH_SACH_CONG_VIEC_ACTION";

export const LAY_DANH_SACH_CONG_VIEC_THEO_TEN_CONG_VIEC_ACTION = "LAY_DANH_SACH_CONG_VIEC_THEO_TEN_CONG_VIEC_ACTION";

export const LAY_THONG_TIN_CHI_TIET_NGUOI_DUNG = "LAY_THONG_TIN_CHI_TIET_NGUOI_DUNG";

export const CAP_NHAT_THONG_TIN_NGUOI_DUNG = "CAP_NHAT_THONG_TIN_NGUOI_DUNG";

export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";

export const TAO_NGUOI_DUNG_MOI = "TAO_NGUOI_DUNG_MOI";

export const XOA_CONG_VIEC_ACTION = "XOA_CONG_VIEC_ACTION";

export const LAY_THONG_TIN_CHI_TIET_CONG_VIEC = "LAY_THONG_TIN_CHI_TIET_CONG_VIEC";



