
export const LAY_DANH_SACH_CONG_VIEC_THEO_TEN_CONG_VIEC_ACTION = "LAY_DANH_SACH_CONG_VIEC_THEO_TEN_CONG_VIEC_ACTION";

export const LAY_THONG_TIN_CHI_TIET_LOAI_CONG_VIEC_CHINH = "LAY_THONG_TIN_CHI_TIET_LOAI_CONG_VIEC_CHINH";

export const LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION = "LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION";

export const LAY_THONG_TIN_CHI_TIET_NGUOI_DUNG = "LAY_THONG_TIN_CHI_TIET_NGUOI_DUNG";

export const LAY_THONG_TIN_CHI_TIET_CONG_VIEC = "LAY_THONG_TIN_CHI_TIET_CONG_VIEC";

export const LAY_DANH_SACH_CONG_VIEC_ACTION = "LAY_DANH_SACH_CONG_VIEC_ACTION";

export const CAP_NHAT_THONG_TIN_NGUOI_DUNG = "CAP_NHAT_THONG_TIN_NGUOI_DUNG";

export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";

export const XOA_CONG_VIEC_ACTION = "XOA_CONG_VIEC_ACTION";

export const DANH_SACH_BINH_LUAN = "DANH_SACH_BINH_LUAN";

export const TAO_NGUOI_DUNG_MOI = "TAO_NGUOI_DUNG_MOI";

export const POPULAR_SERVICES = "POPULAR_SERVICES";

export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";

export const DISPLAY_LOADING = "DISPLAY_LOADING";

export const JOB_NAME_SEARCH = "JOB_NAME_SEARCH";

export const ONLINE_SELLERS = "ONLINE_SELLERS";

export const DANG_KY_ACTION = "DANG_KY_ACTION";

export const LOCAL_SELLERS = "LOCAL_SELLERS";

export const HIDE_LOADING = "HIDE_LOADING";

export const PRO_SERVICES = "PRO_SERVICES";

export const FINISH_JOB = "FINISH_JOB";















