export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";

export const DANG_KY_ACTION = "DANG_KY_ACTION";

export const LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION = "LAY_CHI_TIET_LOAI_CONG_VIEC_CHINH_ACTION";

export const DISPLAY_LOADING = "DISPLAY_LOADING";

export const HIDE_LOADING = "HIDE_LOADING";